server:
  port:9001
spring:
  datasource: jdbc:mysql://localhost:3306/scd?useSSL=false
  username: root
  password: admin
  driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
